apiVersion: v2
name: learning-platform
description: A Helm chart for the Learning Platform Application
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - learning-platform
  - fastapi
  - postgresql
  - react
maintainers:
  - name: Kareem
